USE [master]
RESTORE DATABASE [t2] FROM  DISK = N'D:\Backup\t2.bak' 
WITH  FILE = 1,  
MOVE N't2' TO N'D:\DATA_REPL\t2.mdf',  
MOVE N't2_log' TO N'D:\LOG_REPL\t2_log.ldf',  
NORECOVERY,  NOUNLOAD,  STATS = 5
GO
RESTORE LOG [t2] FROM  DISK = N'D:\BACKUP\t2.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
GO



:connect TSQL03\REPL

BACKUP DATABASE [t2] TO  DISK = N'E:\BACKUP\t2.bak' WITH NOFORMAT, NOINIT,  NAME = N't2-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10
GO

:connect TSQL05\REPL

USE [master]
RESTORE DATABASE [t2] FROM  DISK = N'E:\BACKUP\t2.bak' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5

GO

:connect TSQL03\REPL

BACKUP LOG [t2] TO  DISK = N'E:\BACKUP\t2.trn' WITH NOFORMAT, NOINIT,  NAME = N't2-LOG Database Backup', 
SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10

:connect TSQL05\REPL

USE [master]
RESTORE LOG [t2] FROM  DISK = N'E:\BACKUP\t2.trn' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5

GO



