CREATE DATABASE [MemOpt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MemOpt', FILENAME = N'C:\SQL_Data\MemOpt.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MemOpt_log', FILENAME = N'C:\SQL_Data\MemOpt_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MemOpt] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [MemOpt] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MemOpt] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MemOpt] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MemOpt] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MemOpt] SET ARITHABORT OFF 
GO
ALTER DATABASE [MemOpt] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MemOpt] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MemOpt] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [MemOpt] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MemOpt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MemOpt] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MemOpt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MemOpt] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MemOpt] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MemOpt] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MemOpt] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MemOpt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MemOpt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MemOpt] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MemOpt] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MemOpt] SET  READ_WRITE 
GO
ALTER DATABASE [MemOpt] SET RECOVERY FULL 
GO
ALTER DATABASE [MemOpt] SET  MULTI_USER 
GO
ALTER DATABASE [MemOpt] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MemOpt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MemOpt] SET DELAYED_DURABILITY = DISABLED 
GO
USE [MemOpt]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [MemOpt]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [MemOpt] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

--======================================================
-- Add MEMORY_OPTIMIZED_DATA Filegroup and Create Memory Optimized Table Template
-- Use the Specify Values for Template Parameters command (Ctrl-Shift-M) to fill in the parameter values below.
-- This template adds a MEMORY_OPTIMIZED_DATA filegroup to the database, and creates a memory optimized table and indexes on the memory optimized table.
-- The database must have a MEMORY_OPTIMIZED_DATA filegroup before the memory optimized table can be created.
--======================================================

USE [MemOpt]
GO

--Add MEMORY_OPTIMIZED_DATA filegroup to the database.
ALTER DATABASE [MemOpt]
ADD FILEGROUP MemOpt_FG CONTAINS MEMORY_OPTIMIZED_DATA

--Add file to the MEMORY_OPTIMIZED_DATA filegroup.
ALTER DATABASE [MemOpt]
ADD FILE
  ( NAME = MemOpt_File,
    FILENAME = N'C:\SQL_Data\MemOpt_mod')
TO FILEGROUP MemOpt_FG

--Drop table if it already exists.
IF OBJECT_ID('dbo.MemOptTab','U') IS NOT NULL
    DROP TABLE dbo.MemOptTab
GO

--Create memory optimized table and indexes on the memory optimized table.
CREATE TABLE dbo.MemOptTab
(
	c1 int NOT NULL, 
	c2 float NOT NULL,
	c3 decimal(10,2) NOT NULL INDEX index_sample_memoryoptimizedtable_c3 NONCLUSTERED (c3), 

   CONSTRAINT PK_sample_memoryoptimizedtable PRIMARY KEY NONCLUSTERED (c1),
   -- See SQL Server Books Online for guidelines on determining appropriate bucket count for the index
   INDEX hash_index_sample_memoryoptimizedtable_c2 HASH (c2) WITH (BUCKET_COUNT = 131072)
) WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA)
GO

sp_help 'dbo.MemOptTab'

insert into dbo.MemOptTab values (1, 0.1, 10.5)