USE [master]
GO

/****** Object:  Database [IrisInsuranceDB]    Script Date: 1/20/2020 7:47:42 PM ******/
CREATE DATABASE [IrisInsuranceDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IrisInsuranceDB', FILENAME = N'C:\MSSQL\DATA\IrisInsuranceDB.mdf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB ), 
 FILEGROUP [MemoryOptimizedFileGroup] CONTAINS MEMORY_OPTIMIZED_DATA  DEFAULT
( NAME = N'mod', FILENAME = N'C:\MSSQL\MO\IrisInsuranceDB_mod' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'IrisInsuranceDB_log', FILENAME = N'C:\MSSQL\LOG\IrisInsuranceDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 524288KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IrisInsuranceDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IrisInsuranceDB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET ARITHABORT ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [IrisInsuranceDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IrisInsuranceDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [IrisInsuranceDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IrisInsuranceDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IrisInsuranceDB] SET  MULTI_USER 
GO

ALTER DATABASE [IrisInsuranceDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IrisInsuranceDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IrisInsuranceDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IrisInsuranceDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [IrisInsuranceDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IrisInsuranceDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [IrisInsuranceDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 8), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 500, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO

USE [IrisInsuranceDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [IrisInsuranceDB] SET  READ_WRITE 
GO


