EXEC sp_fkeys 'Bank'
go

SELECT OBJECT_NAME(REFERENCED_OBJECT_ID) AS MASTERTABLE 
	FROM SYS.FOREIGN_KEY_COLUMNS A JOIN SYS.COLUMNS B ON A.PARENT_COLUMN_ID =B.COLUMN_ID AND A.PARENT_OBJECT_ID=B.OBJECT_ID 
		JOIN SYS.COLUMNS C ON A.CONSTRAINT_COLUMN_ID=C.COLUMN_ID AND A.REFERENCED_OBJECT_ID=C.OBJECT_ID 
WHERE OBJECT_NAME(PARENT_OBJECT_ID)='Bank'


alter TABLE [dbo].[BankAcc]   disable FOREIGN KEY([bank])
ALTER TABLE [dbo].[BankAcc]
NOCHECK CONSTRAINT FK__BankAcc__bank__4CA06362;  
GO  

ALTER TABLE [dbo].[BankAcc]
drop CONSTRAINT [FK__BankAcc__bank__797309D9]
GO  

sp_help 'Bank'
sp_help 'MOEX_EacClient.dbo.BankAcc'