CREATE MESSAGE TYPE [ProcRequestMessageType] VALIDATION = NONE
go
CREATE CONTRACT [ProcContract] ([ProcRequestMessageType] SENT BY INITIATOR)
GO

CREATE QUEUE [dbo].[ProcResponseQueue] WITH STATUS = ON , RETENTION = OFF , POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
go
CREATE SERVICE [ProcResponseService]  ON QUEUE [dbo].[ProcResponseQueue] ([DEFAULT])
GO

CREATE QUEUE [dbo].[ProcQueue1] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue1Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
go
CREATE SERVICE [ProcService1]  ON QUEUE [dbo].[ProcQueue1] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue2] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue2Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
CREATE SERVICE [ProcService2]  ON QUEUE [dbo].[ProcQueue2] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue3] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue3Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
go
CREATE SERVICE [ProcService3]  ON QUEUE [dbo].[ProcQueue3] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue4] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue4Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
go
CREATE SERVICE [ProcService4]  ON QUEUE [dbo].[ProcQueue4] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue5] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue5Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
go
CREATE SERVICE [ProcService5]  ON QUEUE [dbo].[ProcQueue5] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue6] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue6Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
CREATE SERVICE [ProcService6]  ON QUEUE [dbo].[ProcQueue6] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue7] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue7Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
CREATE SERVICE [ProcService7]  ON QUEUE [dbo].[ProcQueue7] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue8] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue8Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
CREATE SERVICE [ProcService8]  ON QUEUE [dbo].[ProcQueue8] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue9] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue9Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
CREATE SERVICE [ProcService9]  ON QUEUE [dbo].[ProcQueue9] ([DEFAULT],[ProcContract])
GO
CREATE QUEUE [dbo].[ProcQueue10] WITH STATUS = ON , RETENTION = OFF , ACTIVATION (  STATUS = ON , PROCEDURE_NAME = [dbo].[spProcQueue10Handler] , MAX_QUEUE_READERS = 24 , EXECUTE AS N'dbo'  ), POISON_MESSAGE_HANDLING (STATUS = ON)  ON [PRIMARY] 
CREATE SERVICE [ProcService10]  ON QUEUE [dbo].[ProcQueue10] ([DEFAULT],[ProcContract])
GO 


